name: PHP CI
on:
  pull_request:
    branches: [ master, develop ]

jobs:

  unit-test:
    name: phpunit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Composer
        uses: php-actions/composer@v5
      # or alternative dependency management
      
      - name: PHPUnit
        uses: php-actions/phpunit@v2